server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB


minio:
  endpoint: http://119.3.215.150:9000
  bucketName: images
  accessKey: admin
  secretKey: admin123456